### ISSUE TITLE
Vietnamese Telex and Number key-based keyboards are now available on your PC

### ISSUE THREAD

**Issue by TheJoeFin** [TheJoeFin/Windows10-Community#51]
Do you write Vietnamese? We want you to have the best possible typing experience, so we’re happy to announce that with this build you can now use Vietnamese Telex and Number-key based (VNI) keyboards for typing Vietnamese! Bringing these keyboard options to PC has been one of the top feature requests in the input space, so we’re looking forward to you trying it out!

Build [18267](https://blogs.windows.com/windowsexperience/2018/10/24/announcing-windows-10-insider-preview-build-18267/#Z7M9qJIALozO6P7i.97)

**Comment by onlysublime** [comment]
you can't imagine how important this is for the Vietnamese language community.  Those keyboards are traditionally used and accepted by the community.  Once I showed people these new keyboards were present, they didn't need the third-party keyboards (some of dubious origin) anymore.
