### ISSUE TITLE
Making Notepad store-updatable

### ISSUE THREAD

**Issue by TheJoeFin** [TheJoeFin/Windows10-Community#98]
Notepad has been a well-loved text editor in Windows for over 30 years. Over the last few releases, we’ve been making a number of small improvements to Notepad based on your feedback (including expanded line ending support, wrap around search, and indicating when there’s unsaved content.) Starting with this build, we’re making a change so that future Notepad updates will be automatically available via the store. This will allow us the flexibility to respond to issues and feedback outside the bounds of Windows releases. As always, if you have any feedback for Notepad, we welcome it in the Feedback Hub under Apps > Notepad.

**Comment by RokeJulianLockhart** [comment]
This should be closed.
